plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.livemictospeaker'
    compileSdk 37
    defaultConfig {
        applicationId "com.example.livemictospeaker"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures { viewBinding true }
}

apply from: rootProject.file('gradle/production-release.gradle')

dependencies {
    implementation project(path: ':ads')
    implementation libs.appcompat
    implementation libs.core
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
    implementation libs.recyclerview
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.test.core
    androidTestImplementation libs.test.rules
    androidTestImplementation libs.test.runner
    implementation libs.lottie
    implementation libs.licenses.dialog
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'
    implementation libs.sdp
    implementation libs.ssp
}
